# This playbook contains example tasks to perform on a fresh Fedora
# installation. 
#
# Copyright (c) 2013-2024 Fabian Affolter <fabian@affolter-engineering.ch>
#
# Licensed under CC BY 3.0. All rights reserved.
#
# Usage: sudo ansible-playbook setup.yml -f 10

---
- hosts: fedora
  user: root
  vars_files:
    - variables/application-versions.yml
    - variables/sensitive.yml

  tasks:
    - include: tasks/motd.yml
    - include: tasks/rpmfusion.yml
    - include: tasks/sshd.yml
    - include: tasks/pxe.yml

  handlers:
   - include: handlers/system.yml
   - include: handlers/services.yml
