# This playbook upgrades all Fedora hosts and initialize a reboot.
#
# Copyright (c) 2013-2019 Fabian Affolter <fabian@affolter-engineering.ch>
#
# Licensed under CC BY 3.0. All rights reserved.
#
---
- hosts: fedora
  user: root

  tasks:
  - name: upgrade all packages
    raw: /usr/bin/dnf -y upgrade

  - name: reboot system
    raw: /usr/sbin/reboot
